trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Bash@3
    displayName: Build extensions
    inputs:
      targetType: inline
      script: >-
        if [ -f extensions.csproj ]

        then
            dotnet build extensions.csproj --output ./bin
        fi
  - task: NodeTool@0
    displayName: Use Node version 16
    inputs:
      versionSpec: 16
      checkLatest: true
  - task: Npm@1
    displayName: Install Application Dependencies
    inputs:
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
  - task: Npm@1
    displayName: Run 'build' script
    inputs:
      command: custom
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
      customCommand: run build --if-present
  - task: Npm@1
    displayName: Remove extraneous packages
    inputs:
      command: custom
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
      customCommand: prune --production
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
